
wg_profile_show:
    pattern:  /{username_slug}
    defaults: { _controller: WrittenGamesApplicationBundle:Profile:show }

wg_profile_edit:
    pattern:  /{username_slug}/edit
    defaults: { _controller: WrittenGamesApplicationBundle:Profile:edit }

wg_profile_username_available:
    pattern:  /{username_slug}/username-available
    defaults: { _controller: WrittenGamesApplicationBundle:Profile:usernameAvailable }

wg_profile_save_username:
    pattern:  /{username_slug}/change-username
    defaults: { _controller: WrittenGamesApplicationBundle:Profile:saveUsername }

wg_profile_save_password:
    pattern:  /{username_slug}/change-password
    defaults: { _controller: WrittenGamesApplicationBundle:Profile:savePassword }

wg_profile_request_change_email:
    pattern:  /{username_slug}/change-email
    defaults: { _controller: WrittenGamesApplicationBundle:Profile:requestChangeEmail }

wg_profile_confirm_change_email:
    pattern:  /{username_slug}/change-email/{confirmation_token}
    defaults: { _controller: WrittenGamesApplicationBundle:Profile:confirmChangeEmail }
