
WrittenGamesApplicationBundle:
    resource: "@WrittenGamesApplicationBundle/Resources/config/routing.yml"
    prefix:   /

openiduser_identities:
    resource: "@WGOpenIdUserBundle/Resources/config/routing/identity.yml"
    prefix:   /openid

