
###########################
# SocialUserBundle Routes #
###########################

userfriendly_social_user_routes:
    resource: "@UserfriendlySocialUserBundle/Resources/config/routing.yml"
    prefix:   /

facebook_login:
    pattern: /login/check-facebook

twitter_login:
    pattern: /login/check-twitter

google_login:
    pattern: /login/check-google

yahoo_login:
    pattern: /login/check-yahoo

############################
# ApplicationBundle routes #
############################

wg_default:
    resource: "@WrittenGamesApplicationBundle/Resources/config/routing/default.yml"
    prefix:   /
