jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
#            id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
                default_target_path: /
            oauth:
                resource_owners:
                    facebook:      "/login/check-facebook"
                    twitter:       "/login/check-twitter"
                    google:        "/login/check-google"
                    yahoo:         "/login/check-yahoo"
                login_path:        /login
                failure_path:      /login
                default_target_path: /
                oauth_user_provider:
                    service: wg.security.user_provider
            logout:
                path: /logout
                target: /
            anonymous:    true
        login:
            pattern:  ^/login$
            security: false
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_SUPER_ADMIN }
        # TODO: add regex for catching only ^/<username>/edit
        - { path: /edit, roles: ROLE_USER }