parameters:
    wg.identity_manager.class: WrittenGames\ApplicationBundle\Security\IdentityManager
    wg.user_provider.class: WrittenGames\ApplicationBundle\Security\UserProvider

services:
    wg.identity_manager:
        class: %wg.identity_manager.class%
        arguments: ['@doctrine.orm.entity_manager']
    wg.user_provider:
        class: %wg.user_provider.class%
        arguments: ['@fos_user.user_manager', '@wg.identity_manager', '@event_dispatcher']